### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by Xiaoyang-Gu** [casbin/casbin-dashboard#135]
Some users mentioned they encounter with the error `[E] [account.go:97]  json: cannot unmarshal object into Go value of type []controllers.userEmailFromGithub`
This because the Casbin-dashboard used an access token (with the User-Agent Go-http-client/1.1) as part of a query parameter to access an endpoint through the GitHub API: [https://api.github.com/user/emails](https://api.github.com/user/emails)   [https://api.github.com/user](https://api.github.com/user)   and using the `access_token` query parameter is deprecated.
To fix this bug, the GitHub Team recommended to use the Authorization HTTP header instead.

**Comment by hsluoyz** [comment]
@438561537 how to fix this issue?

**Comment by 438561537** [comment]
@hsluoyz I had made the pr #136  to fix this issue. 
As the Github team mentioned, I use the Authorization HTTP header `request1, _ := http.NewRequest("GET", "https://api.github.com/user/emails", nil)`     `request1.Header.Set("Authorization", "token "+token.AccessToken)` instead of using access_token as part of a query parameter `response, err := http.Get("https://api.github.com/user/emails?access_token=" + token.AccessToken)`.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-dashboard/pull/139
